package bfs.TeamProj.domain;

import io.swagger.annotations.ApiModelProperty;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.persistence.Id;
import java.util.List;

@Document(collection = "owners")
public class Owner{

    @Id
    @ApiModelProperty(notes = "ID generated by MongoDB")
    private String id;

    @ApiModelProperty(notes = "Owner's name")
    private String name;

    List<Pet> pets;
}
