package bfs.TeamProj.domain;

import io.swagger.annotations.ApiModelProperty;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.persistence.Id;

@Document(collection = "pets")
public class Pet {

    @Id
    @ApiModelProperty(notes = "ID generated by MongoDB")
    private String id;

    @ApiModelProperty(notes = "Pet's name")
    private String name;

    @ApiModelProperty(notes = "Pet's species")
    private String species;


}
